"use client";
import { useEffect, useState } from "react";
import { formatRupiah } from "@/lib/utils";

type Tx={id:string;order_id:string;order_number:string;customer_no:string;product_name:string;status:string;provider_status:string|null;response_code:string|null;serial_number:string|null;provider_message:string|null;attempt_count:number;created_at:string;next_retry_at:string|null};
const badge=(s:string)=>s==='SUCCESS'?'bg-emerald-100 text-emerald-700':s==='FAILED'?'bg-red-100 text-red-700':s==='PROCESSING'?'bg-gold-100 text-gold-700':'bg-amber-100 text-amber-700';
export default function Monitoring(){const [rows,setRows]=useState<Tx[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState<string|null>(null);const [filter,setFilter]=useState('ALL');
 async function load(){setLoading(true);const r=await fetch('/api/admin/ppob/monitoring',{cache:'no-store'});if(r.ok){const d=await r.json();setRows(d.transactions||[]);}setLoading(false)} useEffect(()=>{load();const t=window.setInterval(load,20000);return()=>window.clearInterval(t)},[]);
 async function retry(id:string){setBusy(id);const r=await fetch(`/api/admin/ppob/retry/${id}`,{method:'POST'});const d=await r.json();if(!r.ok)alert(d.message||'Retry gagal');await load();setBusy(null)}
 const shown=filter==='ALL'?rows:rows.filter(x=>x.status===filter); const counts=Object.fromEntries(['PROCESSING','SUCCESS','FAILED'].map(s=>[s,rows.filter(x=>x.status===s).length]));
 return <div className="space-y-5"><div className="rounded-3xl bg-gradient-to-r from-slate-950 via-slate-900 to-zinc-950 p-6 text-white"><p className="text-xs font-black uppercase tracking-[.2em] text-amber-300">PPOB MONITORING</p><h1 className="mt-2 text-2xl font-black">Monitoring Transaksi</h1><p className="mt-2 text-sm text-white/65">Pantau status provider, percobaan retry, dan SN/token dari satu halaman.</p></div><div className="grid grid-cols-3 gap-3">{[['PROCESSING','🔄 Diproses'],['SUCCESS','✅ Berhasil'],['FAILED','❌ Gagal']].map(([s,l])=><button key={s} onClick={()=>setFilter(filter===s?'ALL':s)} className="rounded-2xl border border-slate-200 bg-white p-4 text-left shadow-sm"><p className="text-xs font-bold text-slate-400">{l}</p><p className="mt-1 text-2xl font-black">{counts[s]||0}</p></button>)}</div><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 p-4"><p className="font-black">Transaksi PPOB {filter!=='ALL'&&`• ${filter}`}</p><button onClick={load} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-black">↻ Refresh</button></div>{loading?<p className="p-6 text-sm text-slate-500">Memuat...</p>:shown.length===0?<p className="p-6 text-sm text-slate-500">Tidak ada transaksi.</p>:<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-400"><tr><th className="p-3">Order</th><th>Produk</th><th>Tujuan</th><th>Status</th><th>Provider</th><th>Percobaan</th><th>Aksi</th></tr></thead><tbody>{shown.map(x=><tr key={x.id} className="border-t border-slate-100"><td className="p-3"><b>{x.order_number}</b><p className="text-[10px] text-slate-400">{new Date(x.created_at).toLocaleString('id-ID')}</p></td><td>{x.product_name}</td><td>{x.customer_no}</td><td><span className={`rounded-full px-2 py-1 text-[10px] font-black ${badge(x.status)}`}>{x.status}</span>{x.response_code&&<p className="mt-1 text-[10px] text-slate-400">RC {x.response_code}</p>}</td><td>{x.provider_status||'-'}{x.provider_message&&<p className="max-w-[220px] truncate text-[10px] text-slate-400">{x.provider_message}</p>}</td><td>{x.attempt_count||0}/3</td><td>{(x.status==='PROCESSING'||x.status==='FAILED')?<button disabled={busy===x.id} onClick={()=>retry(x.id)} className="rounded-lg bg-gold-600 px-3 py-2 text-xs font-black text-white disabled:opacity-50">{busy===x.id?'Memproses...':'Retry'}</button>:x.serial_number?<span className="font-mono text-xs font-bold">{x.serial_number}</span>:<span className="text-slate-400">—</span>}</td></tr>)}</tbody></table></div>}</section></div>}
