-- AIDIL STORE v36 — Platform expansion after v35.
-- v35 already owns topup_fee_settings (single global config). v36 keeps it intact and adds per-method fees.

create table if not exists public.topup_fee_methods (
  payment_group text primary key check (payment_group in ('qris','bank','bank_digital')),
  enabled boolean not null default true,
  fee_type text not null default 'FIXED' check (fee_type in ('FIXED','PERCENTAGE')),
  fee_value numeric(12,4) not null default 0 check (fee_value >= 0),
  min_topup bigint not null default 10000 check (min_topup > 0),
  max_topup bigint not null default 10000000 check (max_topup >= min_topup),
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id) on delete set null
);
insert into public.topup_fee_methods(payment_group) values ('qris'),('bank'),('bank_digital') on conflict do nothing;
alter table public.topup_fee_methods enable row level security;
revoke all on public.topup_fee_methods from anon,authenticated;
drop policy if exists "topup_fee_methods_admin_read" on public.topup_fee_methods;
create policy "topup_fee_methods_admin_read" on public.topup_fee_methods for select to authenticated using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('ADMIN','SUPER_ADMIN')));

alter table public.topups add column if not exists fee_group text;
update public.topups set fee_group=case when lower(coalesce(payment_method,''))='qris' then 'qris' when lower(coalesce(payment_method,'')) in ('bnc_va','sampoerna_va','maybank_va') then 'bank_digital' else 'bank' end where fee_group is null;

create table if not exists public.site_announcements (id uuid primary key default extensions.uuid_generate_v4(),title text not null default 'Info AIDIL STORE',message text not null,is_active boolean not null default true,updated_by uuid references auth.users(id) on delete set null,updated_at timestamptz not null default now());
create table if not exists public.home_banners (id uuid primary key default extensions.uuid_generate_v4(),title text not null,description text,file_url text not null,file_type text not null default 'image',href text,sort_order integer not null default 0,is_active boolean not null default true,updated_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.testimonials (id uuid primary key default extensions.uuid_generate_v4(),user_id uuid references auth.users(id) on delete set null,display_name text not null,message text not null,rating integer not null default 5 check(rating between 1 and 5),is_approved boolean not null default false,created_at timestamptz not null default now());
create table if not exists public.product_favorites (user_id uuid not null references auth.users(id) on delete cascade,product_id uuid not null references public.products(id) on delete cascade,created_at timestamptz not null default now(),primary key(user_id,product_id));
create table if not exists public.referrals (id uuid primary key default extensions.uuid_generate_v4(),referrer_id uuid not null unique references auth.users(id) on delete cascade,code text not null unique,created_at timestamptz not null default now());
create table if not exists public.referral_uses (id uuid primary key default extensions.uuid_generate_v4(),referral_id uuid not null references public.referrals(id) on delete cascade,referred_user_id uuid not null unique references auth.users(id) on delete cascade,registered_at timestamptz not null default now(),qualified_at timestamptz,qualifying_order_id uuid references public.orders(id) on delete set null,unique(referral_id,referred_user_id));
create table if not exists public.referral_rewards (id uuid primary key default extensions.uuid_generate_v4(),referral_id uuid not null references public.referrals(id) on delete cascade,threshold integer not null default 20,reward_amount bigint not null default 5000,qualified_count integer not null default 0,claimed_at timestamptz,created_at timestamptz not null default now(),unique(referral_id,threshold));
create table if not exists public.missions (id uuid primary key default extensions.uuid_generate_v4(),title text not null,description text not null,reward_amount bigint not null default 0 check(reward_amount>=0),image_url text,mission_type text not null default 'transaction_count',target_count integer not null default 1 check(target_count>0),target_method text,is_active boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.mission_progress (mission_id uuid not null references public.missions(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,progress_count integer not null default 0,completed_at timestamptz,claimed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(mission_id,user_id));
create table if not exists public.kyc_verifications (user_id uuid primary key references auth.users(id) on delete cascade,status text not null default 'PENDING' check(status in ('PENDING','SUBMITTED','VERIFIED','REJECTED')),ktp_path text,kk_path text,rejection_reason text,submitted_at timestamptz,reviewed_at timestamptz,reviewed_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.user_app_settings (user_id uuid primary key references auth.users(id) on delete cascade,transaction_pin_hash text,app_pin_hash text,receipt_paper text not null default '58mm',receipt_header text,receipt_footer text,show_receipt_settings boolean not null default true,login_otp_email boolean not null default false,email_notifications boolean not null default true,updated_at timestamptz not null default now());
create table if not exists public.bank_transfer_services (id uuid primary key default extensions.uuid_generate_v4(),name text not null,provider text,logo_url text,description text,admin_fee bigint not null default 0 check(admin_fee>=0),is_active boolean not null default false,requires_kyc boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.category_media (category_key text primary key,title text not null,icon_url text,updated_by uuid references auth.users(id) on delete set null,updated_at timestamptz not null default now());
create table if not exists public.wallet_adjustments (id uuid primary key default extensions.uuid_generate_v4(),user_id uuid not null references auth.users(id) on delete cascade,amount bigint not null,reason text not null,admin_id uuid not null references auth.users(id) on delete restrict,created_at timestamptz not null default now());
create index if not exists idx_missions_active on public.missions(is_active,created_at desc);
create index if not exists idx_referral_uses_referral on public.referral_uses(referral_id,qualified_at);
create index if not exists idx_testimonials_approved on public.testimonials(is_approved,created_at desc);
create index if not exists idx_banners_active_order on public.home_banners(is_active,sort_order,created_at desc);

alter table public.site_announcements enable row level security;alter table public.home_banners enable row level security;alter table public.testimonials enable row level security;alter table public.product_favorites enable row level security;alter table public.referrals enable row level security;alter table public.referral_uses enable row level security;alter table public.referral_rewards enable row level security;alter table public.missions enable row level security;alter table public.mission_progress enable row level security;alter table public.kyc_verifications enable row level security;alter table public.user_app_settings enable row level security;alter table public.bank_transfer_services enable row level security;alter table public.category_media enable row level security;alter table public.wallet_adjustments enable row level security;

do $$ begin
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='site_announcements' and policyname='public_active_announcement') then create policy "public_active_announcement" on public.site_announcements for select using(is_active=true);end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='home_banners' and policyname='public_active_banners') then create policy "public_active_banners" on public.home_banners for select using(is_active=true);end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='testimonials' and policyname='public_approved_testimonials') then create policy "public_approved_testimonials" on public.testimonials for select using(is_approved=true);end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='product_favorites' and policyname='own_favorites') then create policy "own_favorites" on public.product_favorites for all using(auth.uid()=user_id) with check(auth.uid()=user_id);end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='referrals' and policyname='own_referral') then create policy "own_referral" on public.referrals for select using(auth.uid()=referrer_id);end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='referral_uses' and policyname='own_referral_uses') then create policy "own_referral_uses" on public.referral_uses for select using(exists(select 1 from public.referrals r where r.id=referral_id and r.referrer_id=auth.uid()));end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='referral_rewards' and policyname='own_referral_rewards') then create policy "own_referral_rewards" on public.referral_rewards for select using(exists(select 1 from public.referrals r where r.id=referral_id and r.referrer_id=auth.uid()));end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='missions' and policyname='active_missions') then create policy "active_missions" on public.missions for select using(is_active=true);end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='mission_progress' and policyname='own_mission_progress') then create policy "own_mission_progress" on public.mission_progress for select using(auth.uid()=user_id);end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='kyc_verifications' and policyname='own_kyc') then create policy "own_kyc" on public.kyc_verifications for select using(auth.uid()=user_id);end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='user_app_settings' and policyname='own_settings') then create policy "own_settings" on public.user_app_settings for all using(auth.uid()=user_id) with check(auth.uid()=user_id);end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='bank_transfer_services' and policyname='active_transfer_services') then create policy "active_transfer_services" on public.bank_transfer_services for select using(is_active=true);end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='category_media' and policyname='category_media_public') then create policy "category_media_public" on public.category_media for select using(true);end if;
end $$;

create or replace function public.admin_adjust_wallet(p_user_id uuid,p_amount bigint,p_reason text,p_admin_id uuid) returns void language plpgsql security definer set search_path=public,extensions as $$ declare w public.wallets%rowtype; ok boolean; ref uuid; begin select exists(select 1 from public.profiles where id=p_admin_id and role in ('ADMIN','SUPER_ADMIN')) into ok;if not ok then raise exception 'ADMIN_ONLY';end if;if p_amount=0 then raise exception 'INVALID_AMOUNT';end if;insert into public.wallets(user_id,balance) values(p_user_id,0) on conflict(user_id) do nothing;select * into w from public.wallets where user_id=p_user_id for update;if w.balance+p_amount<0 then raise exception 'INSUFFICIENT_BALANCE';end if;ref=extensions.uuid_generate_v4();update public.wallets set balance=balance+p_amount,updated_at=now() where id=w.id;insert into public.wallet_transactions(wallet_id,type,amount,balance_before,balance_after,reference_type,reference_id,description) values(w.id,case when p_amount>0 then 'TOPUP' else 'REFUND' end,p_amount,w.balance,w.balance+p_amount,'admin_adjustment',ref,p_reason);insert into public.wallet_adjustments(user_id,amount,reason,admin_id) values(p_user_id,p_amount,p_reason,p_admin_id);end $$;
revoke all on function public.admin_adjust_wallet(uuid,bigint,text,uuid) from public,anon,authenticated;grant execute on function public.admin_adjust_wallet(uuid,bigint,text,uuid) to authenticated,service_role;

create or replace function public.process_referral_qualification(p_referred_user uuid,p_order_id uuid) returns void language plpgsql security definer set search_path=public,extensions as $$ declare u public.referral_uses%rowtype;r public.referrals%rowtype;cnt integer;rw public.referral_rewards%rowtype;w public.wallets%rowtype;begin select * into u from public.referral_uses where referred_user_id=p_referred_user and qualified_at is null for update;if not found then return;end if;select * into r from public.referrals where id=u.referral_id for update;update public.referral_uses set qualified_at=now(),qualifying_order_id=p_order_id where id=u.id;select count(*) into cnt from public.referral_uses where referral_id=r.id and qualified_at is not null;insert into public.referral_rewards(referral_id,threshold,reward_amount,qualified_count) values(r.id,20,5000,cnt) on conflict(referral_id,threshold) do update set qualified_count=excluded.qualified_count;select * into rw from public.referral_rewards where referral_id=r.id and threshold=20 for update;if cnt>=rw.threshold and rw.claimed_at is null then insert into public.wallets(user_id,balance) values(r.referrer_id,0) on conflict(user_id) do nothing;select * into w from public.wallets where user_id=r.referrer_id for update;update public.wallets set balance=balance+rw.reward_amount,updated_at=now() where id=w.id;insert into public.wallet_transactions(wallet_id,type,amount,balance_before,balance_after,reference_type,reference_id,description) values(w.id,'TOPUP',rw.reward_amount,w.balance,w.balance+rw.reward_amount,'referral_reward',rw.id,'Bonus referral 20 teman');update public.referral_rewards set claimed_at=now() where id=rw.id;insert into public.notifications(user_id,title,message,reference_type,reference_id) values(r.referrer_id,'Bonus Referral Cair','Bonus referral Rp5.000 sudah masuk ke saldo.','referral_reward',rw.id);end if;end $$;
revoke all on function public.process_referral_qualification(uuid,uuid) from public,anon;grant execute on function public.process_referral_qualification(uuid,uuid) to authenticated,service_role;

create or replace function public.process_mission_event(p_user_id uuid,p_event_type text,p_event_method text default null) returns void language plpgsql security definer set search_path=public,extensions as $$ declare m public.missions%rowtype;p public.mission_progress%rowtype;w public.wallets%rowtype;begin for m in select * from public.missions where is_active=true and (target_method is null or lower(target_method)=lower(coalesce(p_event_method,''))) and (mission_type=p_event_type or mission_type='transaction_count') loop insert into public.mission_progress(mission_id,user_id,progress_count) values(m.id,p_user_id,0) on conflict(mission_id,user_id) do nothing;select * into p from public.mission_progress where mission_id=m.id and user_id=p_user_id for update;if p.claimed_at is not null then continue;end if;update public.mission_progress set progress_count=least(m.target_count,p.progress_count+1),updated_at=now(),completed_at=case when p.progress_count+1>=m.target_count then coalesce(completed_at,now()) else completed_at end where mission_id=m.id and user_id=p_user_id;if p.progress_count+1>=m.target_count and m.reward_amount>0 then insert into public.wallets(user_id,balance) values(p_user_id,0) on conflict(user_id) do nothing;select * into w from public.wallets where user_id=p_user_id for update;update public.wallets set balance=balance+m.reward_amount,updated_at=now() where id=w.id;insert into public.wallet_transactions(wallet_id,type,amount,balance_before,balance_after,reference_type,reference_id,description) values(w.id,'TOPUP',m.reward_amount,w.balance,w.balance+m.reward_amount,'mission',m.id,'Hadiah misi: '||m.title);update public.mission_progress set claimed_at=now() where mission_id=m.id and user_id=p_user_id;insert into public.notifications(user_id,title,message,reference_type,reference_id) values(p_user_id,'Misi Selesai','Hadiah Rp'||to_char(m.reward_amount,'FM999G999G999')||' sudah masuk ke saldo.','mission',m.id);end if;end loop;end $$;
revoke all on function public.process_mission_event(uuid,text,text) from public,anon;grant execute on function public.process_mission_event(uuid,text,text) to authenticated,service_role;

create or replace function public.trg_topup_events() returns trigger language plpgsql security definer set search_path=public,extensions as $$ begin if new.status='APPROVED' and old.status is distinct from new.status then perform public.process_mission_event(new.user_id,'topup_approved',new.payment_method);end if;return new;end $$;
drop trigger if exists trg_topup_mission on public.topups;create trigger trg_topup_mission after update of status on public.topups for each row execute function public.trg_topup_events();
create or replace function public.trg_referral_order() returns trigger language plpgsql security definer set search_path=public,extensions as $$ begin if new.status='COMPLETED' and old.status is distinct from new.status then perform public.process_referral_qualification(new.user_id,new.id);perform public.process_mission_event(new.user_id,'transaction_count',null);end if;return new;end $$;
drop trigger if exists trg_referral_order on public.orders;create trigger trg_referral_order after update of status on public.orders for each row execute function public.trg_referral_order();

insert into public.category_media(category_key,title) values('pulsa','Pulsa'),('paket-data','Paket Data'),('top-up-game','Top Up Game'),('e-wallet','E-Wallet'),('voucher','Voucher'),('pln','PLN'),('streaming','Streaming'),('tv','TV'),('gas','Gas'),('media-sosial','Media Sosial'),('hotel','Hotel'),('transfer-uang','Transfer Uang / Kirim Uang'),('pln-pascabayar','PLN Pascabayar'),('pdam','PDAM'),('bpjs-kesehatan','BPJS Kesehatan'),('multifinance','Multifinance'),('pbb','PBB'),('samsat','SAMSAT') on conflict(category_key) do nothing;
insert into storage.buckets(id,name,public) values('kyc-private','kyc-private',false) on conflict(id) do nothing;
insert into storage.buckets(id,name,public) values('site-media','site-media',true) on conflict(id) do nothing;
do $$ begin
 if not exists(select 1 from pg_policies where schemaname='storage' and tablename='objects' and policyname='kyc_owner_insert') then create policy "kyc_owner_insert" on storage.objects for insert to authenticated with check(bucket_id='kyc-private' and (storage.foldername(name))[1]=auth.uid()::text);end if;
 if not exists(select 1 from pg_policies where schemaname='storage' and tablename='objects' and policyname='kyc_owner_select') then create policy "kyc_owner_select" on storage.objects for select to authenticated using(bucket_id='kyc-private' and (storage.foldername(name))[1]=auth.uid()::text);end if;
 if not exists(select 1 from pg_policies where schemaname='storage' and tablename='objects' and policyname='site_media_public') then create policy "site_media_public" on storage.objects for select using(bucket_id='site-media');end if;
end $$;

create or replace function public.attach_referral_on_signup() returns trigger language plpgsql security definer set search_path=public,extensions as $$ declare r public.referrals%rowtype;code text;begin code=coalesce(new.raw_user_meta_data->>'referral_code',new.raw_user_meta_data->>'ref','');if code<>'' then select * into r from public.referrals rr where upper(rr.code)=upper(code) limit 1;if found and r.referrer_id<>new.id then insert into public.referral_uses(referral_id,referred_user_id) values(r.id,new.id) on conflict(referred_user_id) do nothing;end if;end if;return new;end $$;
drop trigger if exists trg_attach_referral on auth.users;create trigger trg_attach_referral after insert on auth.users for each row execute function public.attach_referral_on_signup();
