"use client";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { Suspense, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import Button from "@/components/Button";
import { useToast } from "@/components/ToastProvider";

function VerifyForm() {
  const supabase = createClient(); const router = useRouter(); const params = useSearchParams(); const toast = useToast();
  const email = (params.get("email") || "").trim().toLowerCase();
  const [token,setToken]=useState(""); const [password,setPassword]=useState(""); const [loading,setLoading]=useState(false); const [resending,setResending]=useState(false); const [done,setDone]=useState(false); const [error,setError]=useState<string|null>(null);
  async function verify(e:React.FormEvent){e.preventDefault();setError(null);if(!email)return setError("Email verifikasi tidak ditemukan. Silakan daftar kembali.");if(!/^\d{6}$/.test(token))return setError("Masukkan kode OTP 6 digit.");if(password.length<6)return setError("Password minimal 6 karakter.");setLoading(true);const{error:otpError}=await supabase.auth.verifyOtp({email,token,type:"email"});if(otpError){setLoading(false);setError("Kode OTP salah atau sudah kedaluwarsa.");return}const{error:passError}=await supabase.auth.updateUser({password});setLoading(false);if(passError){setError(passError.message);return}setDone(true);toast.show("Email berhasil diverifikasi.","success");setTimeout(()=>router.replace("/dashboard"),900)}
  async function resend(){if(!email||resending)return;setResending(true);setError(null);const{error}=await supabase.auth.signInWithOtp({email,options:{shouldCreateUser:false}});setResending(false);if(error)setError(error.message);else toast.show("OTP baru sudah dikirim ke email.","success")}
  if(done)return <div className="mx-auto max-w-md rounded-[2rem] border bg-white p-8 text-center shadow-xl"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-3xl bg-emerald-50 text-3xl">✓</div><h1 className="mt-5 text-2xl font-black">Email terverifikasi</h1><p className="mt-2 text-sm text-slate-500">Akunmu siap digunakan. Mengarahkan ke beranda...</p></div>;
  return <div className="mx-auto max-w-md rounded-[2rem] border border-slate-200 bg-white p-6 shadow-2xl sm:p-9"><div className="mb-6 flex items-center gap-3"><img src="/aidil-logo.png" className="h-12 w-12 rounded-2xl bg-slate-50 p-1" alt="AIDIL STORE"/><div><p className="text-xs font-black uppercase tracking-widest text-gold-600">AIDIL STORE</p><h1 className="text-xl font-black">Verifikasi Email</h1></div></div><p className="text-sm leading-6 text-slate-500">Masukkan OTP 6 digit yang dikirim ke <b className="text-slate-800">{email||"email kamu"}</b>. Verifikasi email dilakukan dengan OTP, bukan tautan.</p><form onSubmit={verify} className="mt-6 space-y-4"><label className="block text-sm font-bold">Kode OTP<input required inputMode="numeric" maxLength={6} value={token} onChange={e=>setToken(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="000000" className="mt-2 w-full rounded-xl border bg-slate-50 px-4 py-3 text-center text-2xl font-black tracking-[.45em]"/></label><label className="block text-sm font-bold">Buat Password<input required minLength={6} type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full rounded-xl border bg-slate-50 px-4 py-3"/></label>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<Button type="submit" loading={loading} className="w-full">Verifikasi & Aktifkan Akun</Button></form><button onClick={resend} disabled={resending} className="mt-4 w-full text-sm font-bold text-gold-600 disabled:opacity-50">{resending?"Mengirim OTP...":"Kirim ulang OTP"}</button><Link href="/login" className="mt-4 block text-center text-sm text-slate-500">Kembali ke Login</Link></div>
}
export default function VerifyEmailPage(){return <Suspense fallback={<div className="mx-auto max-w-md rounded-3xl bg-white p-8">Memuat...</div>}><VerifyForm/></Suspense>}
