"use client";
import { useEffect, useState } from "react";
import Button from "@/components/Button";
import { useToast } from "@/components/ToastProvider";

const empty = { name: "", scope_type: "GLOBAL", scope_key: "*", fee_type: "FIXED", fee_value: 0, min_fee: "", max_fee: "", min_amount: 0, max_amount: "", priority: 0, is_active: true };
const rupiah = (n: any) => `Rp${Number(n || 0).toLocaleString("id-ID")}`;

export default function PricingAdmin() {
  const toast = useToast(); const [rules,setRules]=useState<any[]>([]); const [form,setForm]=useState<any>(empty); const [loading,setLoading]=useState(true);
  async function load(){setLoading(true); const r=await fetch('/api/admin/pricing'); const j=await r.json(); setRules(j.rules||[]); setLoading(false)}
  useEffect(()=>{load()},[]);
  async function save(){const r=await fetch('/api/admin/pricing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({value:form})});const j=await r.json();if(!r.ok)toast.show(j.message||'Gagal menyimpan','error');else{toast.show('Rule harga tersimpan','success');setForm(empty);load()}}
  async function remove(id:string){const r=await fetch('/api/admin/pricing',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});if(r.ok){toast.show('Rule dihapus','success');load()}else toast.show('Gagal menghapus','error')}
  if(loading)return <div>Memuat...</div>;
  return <div className="space-y-5"><div><p className="section-kicker">Mesin harga PPOB</p><h1 className="text-2xl font-black">Harga & Biaya Transaksi</h1><p className="mt-1 text-sm text-slate-500">Atur biaya layanan AIDIL STORE di atas harga provider. Rule SKU mengalahkan brand, brand mengalahkan kategori, kategori mengalahkan global.</p></div>
  <div className="rounded-2xl border bg-white p-5"><h2 className="font-black">Tambah / Edit Rule</h2><div className="mt-3 grid gap-3 md:grid-cols-4"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Nama rule" className="rounded-xl border p-3"/><select value={form.scope_type} onChange={e=>setForm({...form,scope_type:e.target.value,scope_key:e.target.value==='GLOBAL'?'*':''})} className="rounded-xl border p-3"><option>GLOBAL</option><option>CATEGORY</option><option>BRAND</option><option>SKU</option></select><input value={form.scope_key} disabled={form.scope_type==='GLOBAL'} onChange={e=>setForm({...form,scope_key:e.target.value})} placeholder="contoh: e-wallet / DANA / SKU" className="rounded-xl border p-3"/><select value={form.fee_type} onChange={e=>setForm({...form,fee_type:e.target.value})} className="rounded-xl border p-3"><option>FIXED</option><option>PERCENTAGE</option></select><input type="number" value={form.fee_value} onChange={e=>setForm({...form,fee_value:Number(e.target.value)})} placeholder="Biaya" className="rounded-xl border p-3"/><input type="number" value={form.min_fee} onChange={e=>setForm({...form,min_fee:e.target.value})} placeholder="Min fee (opsional)" className="rounded-xl border p-3"/><input type="number" value={form.max_fee} onChange={e=>setForm({...form,max_fee:e.target.value})} placeholder="Max fee (opsional)" className="rounded-xl border p-3"/><input type="number" value={form.min_amount} onChange={e=>setForm({...form,min_amount:Number(e.target.value)})} placeholder="Mulai nominal" className="rounded-xl border p-3"/><input type="number" value={form.max_amount} onChange={e=>setForm({...form,max_amount:e.target.value})} placeholder="Batas nominal (opsional)" className="rounded-xl border p-3"/><input type="number" value={form.priority} onChange={e=>setForm({...form,priority:Number(e.target.value)})} placeholder="Prioritas" className="rounded-xl border p-3"/><label className="flex items-center gap-2 rounded-xl border p-3 text-sm"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/> Aktif</label><Button onClick={save}>Simpan Rule</Button></div></div>
  <div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b text-left text-xs text-slate-400"><th className="p-4">Rule</th><th className="p-4">Scope</th><th className="p-4">Biaya</th><th className="p-4">Nominal</th><th className="p-4">Prioritas</th><th className="p-4">Status</th><th className="p-4"/></tr></thead><tbody>{rules.map(r=><tr key={r.id} className="border-b last:border-0"><td className="p-4"><b>{r.name}</b></td><td className="p-4">{r.scope_type}<div className="text-xs text-slate-400">{r.scope_key}</div></td><td className="p-4 font-bold">{r.fee_type==='PERCENTAGE'?`${r.fee_value}%`:rupiah(r.fee_value)}</td><td className="p-4">{rupiah(r.min_amount)} - {r.max_amount?rupiah(r.max_amount):'tanpa batas'}</td><td className="p-4">{r.priority}</td><td className="p-4">{r.is_active?'Aktif':'Nonaktif'}</td><td className="p-4"><button onClick={()=>remove(r.id)} className="text-xs font-bold text-red-600">Hapus</button></td></tr>)}</tbody></table></div></div>
}
