"use client";
import { useEffect, useMemo, useState } from "react";

const rupiah=(n:number)=>`Rp${Number(n||0).toLocaleString("id-ID")}`;
const periods=[['day','Hari ini'],['week','7 hari'],['month','30 hari']] as const;
export default function FinancePage(){
 const [period,setPeriod]=useState<'day'|'week'|'month'>('month'); const [data,setData]=useState<any>(null); const [loading,setLoading]=useState(true);
 async function load(){setLoading(true); const r=await fetch(`/api/admin/finance?period=${period}`,{cache:'no-store'}); const j=await r.json(); setData(j); setLoading(false)}
 useEffect(()=>{load()},[period]);
 const max=Math.max(...(data?.daily||[]).map((x:any)=>Number(x.gross||0)),1);
 const exportCsv=()=>{const now=new Date(); const end=now.toISOString().slice(0,10); const start=new Date(now); start.setDate(start.getDate()-(period==='day'?0:period==='week'?6:29)); const a=document.createElement('a');a.href=`/api/admin/finance/export?from=${start.toISOString().slice(0,10)}&to=${end}`;a.download=`aidil-store-financial-${start.toISOString().slice(0,10)}-${end}.csv`;a.click()};
 if(loading)return <div className="rounded-2xl border bg-white p-6 text-sm text-slate-500">Memuat Financial Dashboard...</div>;
 if(data?.message)return <div className="rounded-2xl border border-red-200 bg-red-50 p-6 text-sm text-red-700">{data.message}</div>;
 const s=data.summary;
 return <div className="space-y-5 pb-10"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="section-kicker">Keuangan</p><h1 className="text-2xl font-black">Financial Dashboard</h1><p className="mt-1 text-sm text-slate-500">Pendapatan fee, penjualan, biaya provider, gateway, dan keuntungan bersih.</p></div><div className="flex gap-2">{periods.map(([v,l])=><button key={v} onClick={()=>setPeriod(v)} className={`rounded-xl px-4 py-2 text-sm font-bold ${period===v?'bg-slate-950 text-white':'border bg-white text-slate-600'}`}>{l}</button>)}<button onClick={exportCsv} className="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-black text-white">↓ Export CSV</button></div></div>
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card title="Penjualan / Gross" value={rupiah(s.gross_sales)}/><Card title="Fee & Margin" value={rupiah(s.fee_revenue)}/><Card title="Biaya Provider" value={rupiah(s.provider_cost)}/><Card title="Keuntungan Bersih" value={rupiah(s.net_profit)} strong/></div>
 <div className="grid gap-3 sm:grid-cols-4"><Mini title="Fee Top Up" value={rupiah(s.topup_fees)}/><Mini title="Biaya Gateway" value={rupiah(s.gateway_cost)}/><Mini title="Order Selesai" value={s.orders}/><Mini title="Top Up" value={s.topups}/><Mini title="Refund" value={s.refunds}/></div>
 <div className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="font-black">Laporan Harian</h2><p className="text-xs text-slate-500">Periode {new Date(data.start).toLocaleDateString('id-ID')} – {new Date(data.end).toLocaleDateString('id-ID')}</p></div><button onClick={load} className="rounded-xl border px-3 py-2 text-xs font-bold">↻ Refresh</button></div><div className="mt-5 space-y-3">{(data.daily||[]).map((x:any)=><div key={x.date}><div className="mb-1 flex justify-between text-xs"><span className="font-bold">{new Date(x.date+'T00:00:00').toLocaleDateString('id-ID',{day:'2-digit',month:'short'})}</span><span>{rupiah(x.gross)}</span></div><div className="h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-slate-900" style={{width:`${Math.max(2,Math.round(x.gross/max*100))}%`}}/></div><div className="mt-1 flex gap-3 text-[10px] text-slate-400"><span>Fee {rupiah(x.fees)}</span><span>Provider {rupiah(x.provider)}</span><span>Profit {rupiah(x.profit)}</span><span>{x.transactions} trx</span></div></div>)}{!data.daily?.length&&<p className="py-8 text-center text-sm text-slate-400">Belum ada transaksi keuangan pada periode ini.</p>}</div></div>
 <div className="rounded-2xl border bg-white p-5"><h2 className="font-black">Riwayat Keuangan</h2><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b text-left text-xs text-slate-400"><th className="p-3">Waktu</th><th className="p-3">Jenis</th><th className="p-3">Gross</th><th className="p-3">Provider</th><th className="p-3">Gateway</th><th className="p-3">Fee</th><th className="p-3">Profit</th></tr></thead><tbody>{(data.rows||[]).slice(0,200).map((r:any)=><tr key={r.id} className="border-b last:border-0"><td className="p-3 text-xs text-slate-500">{new Date(r.occurred_at).toLocaleString('id-ID')}</td><td className="p-3 font-bold">{r.event_type}</td><td className="p-3">{rupiah(r.gross_amount)}</td><td className="p-3">{rupiah(r.provider_cost)}</td><td className="p-3">{rupiah(r.gateway_cost)}</td><td className="p-3">{rupiah(r.fee_revenue)}</td><td className="p-3 font-black">{rupiah(r.net_profit)}</td></tr>)}</tbody></table></div></div>
 <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-900"><b>Catatan laporan:</b> biaya provider hanya dihitung jika tersedia di data PPOB. Untuk produk non-PPOB yang tidak memiliki data modal, angka keuntungan merupakan kontribusi berdasarkan biaya yang diketahui, bukan laba bersih akuntansi. Biaya gateway dicatat terpisah. Fee Top Up dihitung dari <code>admin_fee</code> dikurangi biaya gateway.</div>
 </div>
}
function Card({title,value,strong=false}:{title:string,value:any,strong?:boolean}){return <div className={`rounded-2xl border bg-white p-5 ${strong?'border-emerald-200 bg-emerald-50/30':''}`}><p className="text-xs font-bold text-slate-500">{title}</p><p className={`mt-1 text-2xl font-black ${strong?'text-emerald-700':''}`}>{value}</p></div>}
function Mini({title,value}:{title:string,value:any}){return <div className="rounded-2xl border bg-slate-50 p-4"><p className="text-[11px] font-bold text-slate-500">{title}</p><p className="mt-1 text-lg font-black">{value}</p></div>}
