import { NextResponse } from 'next/server';
import { z } from 'zod';
import { createClient } from '@/lib/supabase/server';
import { createAdminClient } from '@/lib/supabase/admin';
const schema=z.object({id:z.string().uuid().optional(),question:z.string().trim().min(3).max(240),answer:z.string().trim().min(3).max(10000),sort_order:z.number().int().min(0).max(9999).default(0),is_active:z.boolean().default(true)});
async function admin(){const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user)return null;const {data:p}=await s.from('profiles').select('role').eq('id',user.id).single();return p&&['ADMIN','SUPER_ADMIN'].includes(p.role)?user:null;}
export async function GET(){const u=await admin();if(!u)return NextResponse.json({message:'Forbidden'},{status:403});const {data,error}=await createAdminClient().from('faqs').select('*').order('sort_order').order('created_at');if(error)return NextResponse.json({message:error.message},{status:500});return NextResponse.json({faqs:data||[]});}
export async function POST(req:Request){const u=await admin();if(!u)return NextResponse.json({message:'Forbidden'},{status:403});const p=schema.safeParse(await req.json().catch(()=>null));if(!p.success)return NextResponse.json({message:'Data FAQ tidak valid.'},{status:400});const a=createAdminClient();const {data,error}=await a.from('faqs').insert({...p.data,updated_by:u.id}).select().single();if(error)return NextResponse.json({message:error.message},{status:400});return NextResponse.json({faq:data});}
export async function PUT(req:Request){const u=await admin();if(!u)return NextResponse.json({message:'Forbidden'},{status:403});const p=schema.extend({id:z.string().uuid()}).safeParse(await req.json().catch(()=>null));if(!p.success)return NextResponse.json({message:'Data FAQ tidak valid.'},{status:400});const {id,...rest}=p.data;const {data,error}=await createAdminClient().from('faqs').update({...rest,updated_by:u.id,updated_at:new Date().toISOString()}).eq('id',id).select().single();if(error)return NextResponse.json({message:error.message},{status:400});return NextResponse.json({faq:data});}
export async function DELETE(req:Request){const u=await admin();if(!u)return NextResponse.json({message:'Forbidden'},{status:403});const id=new URL(req.url).searchParams.get('id');if(!id)return NextResponse.json({message:'ID wajib.'},{status:400});const {error}=await createAdminClient().from('faqs').delete().eq('id',id);if(error)return NextResponse.json({message:error.message},{status:400});return NextResponse.json({ok:true});}
