import {NextResponse} from 'next/server';import {createClient} from '@/lib/supabase/server';import {createAdminClient} from '@/lib/supabase/admin';
async function admin(){const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user)return null;const {data:p}=await s.from('profiles').select('role').eq('id',user.id).single();return p&&['ADMIN','SUPER_ADMIN'].includes(p.role)?user:null}
export async function GET(){if(!await admin())return NextResponse.json({message:'Unauthorized'},{status:401});const a=createAdminClient();const [fees,ann,banners,testimonials,missions,transfer,cats]=await Promise.all([a.from('topup_fee_settings').select('*').order('payment_method'),a.from('site_announcements').select('*').order('updated_at',{ascending:false}).limit(1),a.from('home_banners').select('*').order('sort_order'),a.from('testimonials').select('*').order('created_at',{ascending:false}),a.from('missions').select('*').order('created_at',{ascending:false}),a.from('bank_transfer_services').select('*').order('created_at',{ascending:false}),a.from('category_media').select('*').order('title')]);return NextResponse.json({fees:fees.data||[],announcement:ann.data?.[0]||null,banners:banners.data||[],testimonials:testimonials.data||[],missions:missions.data||[],transfer:transfer.data||[],categories:cats.data||[]})}
export async function POST(req:Request){const user=await admin();if(!user)return NextResponse.json({message:'Unauthorized'},{status:401});const body=await req.json().catch(()=>null);const a=createAdminClient();const type=body?.type;let result:any;
if(type==='fee'){result=await a.from('topup_fee_settings').upsert({...body.value,updated_by:user.id,updated_at:new Date().toISOString()},{onConflict:'payment_method'});}
else if(type==='announcement'){const v={title:body.value.title,message:body.value.message,is_active:!!body.value.is_active,updated_by:user.id,updated_at:new Date().toISOString()};const {data:old}=await a.from('site_announcements').select('id').limit(1).maybeSingle();result=old?await a.from('site_announcements').update(v).eq('id',old.id):await a.from('site_announcements').insert(v);}
else if(type==='banner'){result=await a.from('home_banners').upsert({...body.value,updated_by:user.id,updated_at:new Date().toISOString()});}
else if(type==='mission'){result=await a.from('missions').upsert({...body.value,updated_at:new Date().toISOString()});}
else if(type==='testimonial'){result=await a.from('testimonials').upsert(body.value);}
else if(type==='transfer'){result=await a.from('bank_transfer_services').upsert({...body.value,updated_at:new Date().toISOString()});}
else if(type==='category'){result=await a.from('category_media').upsert({...body.value,updated_by:user.id,updated_at:new Date().toISOString()});}
else return NextResponse.json({message:'Unknown type'},{status:400});
if(result?.error)return NextResponse.json({message:result.error.message},{status:400});return NextResponse.json({ok:true});}
