"use client";

import { Suspense, useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { useToast } from "@/components/ToastProvider";
import Button from "@/components/Button";
import EmptyState from "@/components/EmptyState";
import { formatDate, humanizeError } from "@/lib/utils";

type Ticket = { id:string; ticket_number:string; subject:string; category:string; priority:string; status:string; last_message_at:string; created_at:string; order_id:string|null };
type Msg = { id:string; sender_role:string; message:string; created_at:string };
const statuses:Record<string,string>={OPEN:"Terbuka",IN_PROGRESS:"Sedang ditangani",WAITING_CUSTOMER:"Menunggu Anda",RESOLVED:"Terselesaikan",CLOSED:"Ditutup"};
const cats=["PAYMENT","TOPUP","PPOB","ORDER","ACCOUNT","PENGADUAN","OTHER"];
const catLabels:Record<string,string>={PENGADUAN:"⚠️ Pengaduan Konsumen (formal)"};

export default function BantuanPage(){
 return <Suspense fallback={<div className="mx-auto max-w-3xl animate-pulse rounded-3xl bg-white p-8">Memuat bantuan...</div>}><BantuanPageInner/></Suspense>;
}
function BantuanPageInner(){
 const supabase=createClient(); const router=useRouter(); const toast=useToast(); const searchParams=useSearchParams();
 const [userId,setUserId]=useState<string|null>(null); const [tickets,setTickets]=useState<Ticket[]>([]); const [selected,setSelected]=useState<Ticket|null>(null); const [messages,setMessages]=useState<Msg[]>([]);
 const [subject,setSubject]=useState(""); const [message,setMessage]=useState(""); const [category,setCategory]=useState("OTHER"); const [orderId,setOrderId]=useState(""); const [sending,setSending]=useState(false); const [loading,setLoading]=useState(true);
 useEffect(()=>{const k=searchParams.get("kategori");if(k&&cats.includes(k))setCategory(k);/* eslint-disable-next-line react-hooks/exhaustive-deps */},[]);
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){router.push("/login?redirectTo=/bantuan");return;}setUserId(user.id);const {data,error}=await supabase.from("support_tickets").select("id,ticket_number,subject,category,priority,status,last_message_at,created_at,order_id").order("last_message_at",{ascending:false});if(error)toast.show(humanizeError(error.message),"error");setTickets((data as Ticket[])||[]);setLoading(false);}
 async function openTicket(t:Ticket){setSelected(t);const {data,error}=await supabase.from("support_ticket_messages").select("id,sender_role,message,created_at").eq("ticket_id",t.id).order("created_at",{ascending:true});if(error)toast.show(humanizeError(error.message),"error");setMessages((data as Msg[])||[]);}
 useEffect(()=>{load();/* eslint-disable-next-line react-hooks/exhaustive-deps */},[]);
 async function createTicket(e:React.FormEvent){e.preventDefault();if(!userId||subject.trim().length<3||message.trim().length<1){toast.show("Judul dan pesan wajib diisi.","error");return;}setSending(true);try{const {data:t,error:e1}=await supabase.rpc("create_support_ticket",{p_subject:subject.trim(),p_category:category,p_order_id:orderId.trim()||null,p_message:message.trim()});if(e1)throw e1;if(!t)throw new Error("Tiket gagal dibuat");toast.show(`Tiket ${t.ticket_number} berhasil dibuat.`,`success`);setSubject("");setMessage("");setOrderId("");await load();const fresh=(await supabase.from("support_tickets").select("id,ticket_number,subject,category,priority,status,last_message_at,created_at,order_id").eq("id",t.id).single()).data as Ticket; if(fresh)await openTicket(fresh);}catch(err:any){toast.show(humanizeError(err?.message),"error")}finally{setSending(false)}}
 async function closeTicket(){if(!selected)return;setSending(true);try{const {data,error}=await supabase.rpc("close_support_ticket",{p_ticket_id:selected.id});if(error)throw error;setSelected(data as Ticket);await load();toast.show("Tiket ditutup.","success");}catch(err:any){toast.show(humanizeError(err?.message),"error")}finally{setSending(false)}}
 async function reopenTicket(){if(!selected)return;setSending(true);try{const {data,error}=await supabase.rpc("reopen_support_ticket",{p_ticket_id:selected.id});if(error)throw error;setSelected(data as Ticket);await load();toast.show("Tiket dibuka kembali.","success");}catch(err:any){toast.show(humanizeError(err?.message),"error")}finally{setSending(false)}}
 async function reply(){if(!selected||!userId||!message.trim())return;setSending(true);try{const {error}=await supabase.from("support_ticket_messages").insert({ticket_id:selected.id,sender_id:userId,sender_role:"USER",message:message.trim(),is_internal:false});if(error)throw error;await supabase.rpc("touch_support_ticket",{p_ticket_id:selected.id,p_sender_role:"USER",p_message:message.trim()});setMessage("");await openTicket(selected);await load();}catch(err:any){toast.show(humanizeError(err?.message),"error")}finally{setSending(false)}}
 if(loading)return <div className="mx-auto max-w-3xl animate-pulse rounded-3xl bg-white p-8">Memuat bantuan...</div>;
 return <div className="mx-auto max-w-5xl animate-page-in space-y-5"><div><p className="text-xs font-black uppercase tracking-[.2em] text-gold-600">Customer Support v51</p><h1 className="mt-1 text-2xl font-black text-slate-900">Pusat Bantuan</h1><p className="mt-1 text-sm text-slate-500">Buat tiket dan lanjutkan percakapan dengan admin AIDIL STORE dalam satu thread.</p></div>
 <div className="grid gap-5 lg:grid-cols-[340px_1fr]">
 <div className="space-y-4"><form onSubmit={createTicket} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-black">Buat tiket baru</h2><label className="mt-3 block text-sm font-medium">Kategori<select value={category} onChange={e=>setCategory(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm">{cats.map(c=><option key={c} value={c}>{catLabels[c]||c}</option>)}</select></label>
{category==="PENGADUAN"&&<p className="mt-2 rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs leading-5 text-rose-700">Ini jalur <b>pengaduan konsumen formal</b> (mis. saldo terpotong tapi pulsa/token tidak masuk), otomatis diprioritaskan. Sertakan ID Order, nominal, dan waktu transaksi agar diproses lebih cepat. Baca hak Anda di <a href="/pengaduan-konsumen" className="underline font-bold">halaman Pengaduan Konsumen</a>.</p>}<label className="mt-3 block text-sm font-medium">Judul<input value={subject} onChange={e=>setSubject(e.target.value)} maxLength={160} placeholder="Contoh: Top Up belum masuk" className="mt-1 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm"/></label><label className="mt-3 block text-sm font-medium">ID Order (opsional)<input value={orderId} onChange={e=>setOrderId(e.target.value)} placeholder="UUID order jika ada" className="mt-1 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm"/></label><label className="mt-3 block text-sm font-medium">Pesan<textarea value={message} onChange={e=>setMessage(e.target.value)} rows={4} maxLength={5000} placeholder="Jelaskan kendala Anda..." className="mt-1 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm"/></label><Button type="submit" className="mt-4 w-full" loading={sending}>Buat Tiket</Button></form>
 <div className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><h2 className="mb-3 font-black">Tiket Saya</h2>{tickets.length===0?<EmptyState title="Belum ada tiket"/>:<div className="space-y-2">{tickets.map(t=><button key={t.id} onClick={()=>openTicket(t)} className={`w-full rounded-2xl border p-3 text-left transition ${selected?.id===t.id?"border-gold-300 bg-gold-50":"border-slate-200 hover:bg-slate-50"}`}><div className="flex items-center justify-between gap-2"><b className="text-sm">{t.ticket_number}</b><span className="rounded-full bg-white px-2 py-1 text-[10px] font-bold">{statuses[t.status]||t.status}</span></div><p className="mt-1 truncate text-sm font-semibold text-slate-700">{t.subject}</p><p className={`mt-1 text-[11px] ${t.category==="PENGADUAN"?"font-bold text-rose-600":"text-slate-400"}`}>{t.category==="PENGADUAN"?"⚠️ PENGADUAN":t.category} · {formatDate(t.last_message_at)}</p></button>)}</div>}</div></div>
 <div className="rounded-3xl border border-slate-200 bg-white shadow-sm">{!selected?<div className="flex min-h-[520px] items-center justify-center p-8 text-center text-sm text-slate-400">Pilih tiket untuk melihat percakapan.</div>:<div className="flex min-h-[520px] flex-col"><div className="border-b border-slate-100 p-5"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-xs font-bold text-gold-600">{selected.ticket_number}</p><h2 className="text-xl font-black">{selected.subject}</h2></div><div className="flex items-center gap-2"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{statuses[selected.status]||selected.status}</span>{selected.status==="CLOSED"?<Button onClick={reopenTicket} loading={sending}>Buka Kembali</Button>:<button onClick={closeTicket} disabled={sending} className="rounded-xl border border-slate-200 px-3 py-1.5 text-xs font-bold text-slate-600">Tutup Tiket</button>}</div></div></div><div className="flex-1 space-y-3 overflow-y-auto p-5">{messages.map(m=><div key={m.id} className={`max-w-[85%] rounded-2xl p-3 ${m.sender_role==="USER"?"ml-auto bg-gold-600 text-white":"bg-slate-100 text-slate-800"}`}><p className="whitespace-pre-wrap text-sm">{m.message}</p><p className={`mt-1 text-[10px] ${m.sender_role==="USER"?"text-gold-100":"text-slate-400"}`}>{m.sender_role==="ADMIN"?"Admin":"Anda"} · {formatDate(m.created_at)}</p></div>)}</div>{!['CLOSED'].includes(selected.status)&&<div className="border-t border-slate-100 p-4"><textarea value={message} onChange={e=>setMessage(e.target.value)} rows={3} placeholder="Tulis balasan..." className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm"/><Button onClick={reply} className="mt-2 w-full" loading={sending}>Kirim Balasan</Button></div>}</div>}</div></div></div>;
}
