"use client";

import { Suspense, useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { useToast } from "@/components/ToastProvider";
import { formatDate, humanizeError } from "@/lib/utils";

type Ticket = { id:string; ticket_number:string; subject:string; category:string; priority:string; status:string; last_message_at:string; created_at:string; order_id:string|null };
type Msg = { id:string; sender_role:string; message:string; created_at:string };
const statuses:Record<string,string>={OPEN:"Terbuka",IN_PROGRESS:"Sedang ditangani",WAITING_CUSTOMER:"Menunggu Anda",RESOLVED:"Terselesaikan",CLOSED:"Ditutup"};
const cats=["PAYMENT","TOPUP","PPOB","ORDER","ACCOUNT","PENGADUAN","OTHER"];
const catLabels:Record<string,string>={PENGADUAN:"⚠️ Pengaduan Konsumen (formal)"};

export default function BantuanPage(){
 return <Suspense fallback={<div className="mx-auto max-w-3xl animate-pulse rounded-3xl border border-app-border bg-app-surface p-8 text-sm text-app-muted">Memuat bantuan...</div>}><BantuanPageInner/></Suspense>;
}
function BantuanPageInner(){
 const supabase=createClient(); const router=useRouter(); const toast=useToast(); const searchParams=useSearchParams();
 const [userId,setUserId]=useState<string|null>(null); const [tickets,setTickets]=useState<Ticket[]>([]); const [selected,setSelected]=useState<Ticket|null>(null); const [messages,setMessages]=useState<Msg[]>([]);
 const [subject,setSubject]=useState(""); const [message,setMessage]=useState(""); const [category,setCategory]=useState("OTHER"); const [orderId,setOrderId]=useState(""); const [sending,setSending]=useState(false); const [loading,setLoading]=useState(true);
 useEffect(()=>{const k=searchParams.get("kategori");if(k&&cats.includes(k))setCategory(k);/* eslint-disable-next-line react-hooks/exhaustive-deps */},[]);
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){router.push("/login?redirectTo=/bantuan");return;}setUserId(user.id);const {data,error}=await supabase.from("support_tickets").select("id,ticket_number,subject,category,priority,status,last_message_at,created_at,order_id").order("last_message_at",{ascending:false});if(error)toast.show(humanizeError(error.message),"error");setTickets((data as Ticket[])||[]);setLoading(false);}
 async function openTicket(t:Ticket){setSelected(t);const {data,error}=await supabase.from("support_ticket_messages").select("id,sender_role,message,created_at").eq("ticket_id",t.id).order("created_at",{ascending:true});if(error)toast.show(humanizeError(error.message),"error");setMessages((data as Msg[])||[]);}
 useEffect(()=>{load();/* eslint-disable-next-line react-hooks/exhaustive-deps */},[]);
 async function createTicket(e:React.FormEvent){e.preventDefault();if(!userId||subject.trim().length<3||message.trim().length<1){toast.show("Judul dan pesan wajib diisi.","error");return;}const trimmedOrderId=orderId.trim();if(!trimmedOrderId){toast.show("ID Order wajib diisi. Kamu bisa menyalin ID Order dari halaman Pesanan Saya.","error");return;}if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(trimmedOrderId)){toast.show("Format ID Order tidak valid. ID Order bisa dilihat di halaman Pesanan Saya.","error");return;}setSending(true);try{const {data:order,error:orderErr}=await supabase.from("orders").select("id").eq("id",trimmedOrderId).maybeSingle();if(orderErr)throw orderErr;if(!order){toast.show("ID Order tidak ditemukan di akunmu.","error");return;}const {data:t,error:e1}=await supabase.rpc("create_support_ticket",{p_subject:subject.trim(),p_category:category,p_order_id:trimmedOrderId,p_message:message.trim()});if(e1)throw e1;if(!t)throw new Error("Tiket gagal dibuat");toast.show(`Tiket ${t.ticket_number} berhasil dibuat.`,`success`);setSubject("");setMessage("");setOrderId("");await load();const fresh=(await supabase.from("support_tickets").select("id,ticket_number,subject,category,priority,status,last_message_at,created_at,order_id").eq("id",t.id).single()).data as Ticket; if(fresh)await openTicket(fresh);}catch(err:any){toast.show(humanizeError(err?.message),"error")}finally{setSending(false)}}
 async function closeTicket(){if(!selected)return;setSending(true);try{const {data,error}=await supabase.rpc("close_support_ticket",{p_ticket_id:selected.id});if(error)throw error;setSelected(data as Ticket);await load();toast.show("Tiket ditutup.","success");}catch(err:any){toast.show(humanizeError(err?.message),"error")}finally{setSending(false)}}
 async function reopenTicket(){if(!selected)return;setSending(true);try{const {data,error}=await supabase.rpc("reopen_support_ticket",{p_ticket_id:selected.id});if(error)throw error;setSelected(data as Ticket);await load();toast.show("Tiket dibuka kembali.","success");}catch(err:any){toast.show(humanizeError(err?.message),"error")}finally{setSending(false)}}
 async function reply(){if(!selected||!userId||!message.trim())return;setSending(true);try{const {error}=await supabase.from("support_ticket_messages").insert({ticket_id:selected.id,sender_id:userId,sender_role:"USER",message:message.trim(),is_internal:false});if(error)throw error;await supabase.rpc("touch_support_ticket",{p_ticket_id:selected.id,p_sender_role:"USER",p_message:message.trim()});setMessage("");await openTicket(selected);await load();}catch(err:any){toast.show(humanizeError(err?.message),"error")}finally{setSending(false)}}
 if(loading)return <div className="mx-auto max-w-3xl animate-pulse rounded-3xl border border-app-border bg-app-surface p-8 text-sm text-app-muted">Memuat bantuan...</div>;
 return <div className="customer-shell"><div className="mx-auto w-full max-w-[480px] animate-page-in space-y-5 lg:max-w-5xl"><div><p className="text-xs font-black uppercase tracking-[.2em] text-app-kicker">Customer Support v51</p><h1 className="mt-1 text-2xl font-black text-app-text">Pusat Bantuan</h1><p className="mt-1 text-sm text-app-muted">Buat tiket dan lanjutkan percakapan dengan admin AIDIL STORE dalam satu thread.</p></div>
 <div className="grid gap-5 lg:grid-cols-[340px_1fr]">
 <div className="space-y-4"><form onSubmit={createTicket} className="rounded-3xl border border-app-border bg-app-surface p-5"><h2 className="font-black text-app-text">Buat tiket baru</h2><label className="mt-3 block text-sm font-medium text-app-text">Kategori<select value={category} onChange={e=>setCategory(e.target.value)} className="mt-1 w-full rounded-xl border border-app-border bg-app-inset px-3 py-2.5 text-sm text-app-text outline-none transition placeholder:text-app-subtle focus:border-gold-400 focus:ring-4 focus:ring-gold-400/20">{cats.map(c=><option key={c} value={c}>{catLabels[c]||c}</option>)}</select></label>
{category==="PENGADUAN"&&<p className="mt-2 rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-xs leading-5 text-red-600 dark:text-red-400">Ini jalur <b>pengaduan konsumen formal</b> (mis. saldo terpotong tapi pulsa/token tidak masuk), otomatis diprioritaskan. Sertakan ID Order, nominal, dan waktu transaksi agar diproses lebih cepat. Baca hak Anda di <a href="/pengaduan-konsumen" className="underline font-bold">halaman Pengaduan Konsumen</a>.</p>}<label className="mt-3 block text-sm font-medium text-app-text">Judul<input value={subject} onChange={e=>setSubject(e.target.value)} maxLength={160} placeholder="Contoh: Top Up belum masuk" className="mt-1 w-full rounded-xl border border-app-border bg-app-inset px-3 py-2.5 text-sm text-app-text outline-none transition placeholder:text-app-subtle focus:border-gold-400 focus:ring-4 focus:ring-gold-400/20"/></label><label className="mt-3 block text-sm font-medium text-app-text">ID Order <span className="text-gold-400">*</span><input value={orderId} onChange={e=>setOrderId(e.target.value)} placeholder="Tempel ID Order dari halaman Pesanan Saya" className="mt-1 w-full rounded-xl border border-app-border bg-app-inset px-3 py-2.5 text-sm text-app-text outline-none transition placeholder:text-app-subtle focus:border-gold-400 focus:ring-4 focus:ring-gold-400/20"/></label><label className="mt-3 block text-sm font-medium text-app-text">Pesan<textarea value={message} onChange={e=>setMessage(e.target.value)} rows={4} maxLength={5000} placeholder="Jelaskan kendala Anda..." className="mt-1 w-full rounded-xl border border-app-border bg-app-inset px-3 py-2.5 text-sm text-app-text outline-none transition placeholder:text-app-subtle focus:border-gold-400 focus:ring-4 focus:ring-gold-400/20"/></label><button type="submit" disabled={sending} className="mt-4 inline-flex min-h-[44px] w-full items-center justify-center gap-2 rounded-xl bg-gold-400 px-4 py-3 text-sm font-black text-zinc-950 transition hover:bg-gold-300 disabled:cursor-not-allowed disabled:opacity-50">{sending&&<span className="h-4 w-4 animate-spin rounded-full border-2 border-zinc-950/30 border-t-zinc-950"/>}Buat Tiket</button></form>
 <div className="rounded-3xl border border-app-border bg-app-surface p-4"><h2 className="mb-3 font-black text-app-text">Tiket Saya</h2>{tickets.length===0?<p className="rounded-2xl border border-app-border bg-app-inset p-4 text-center text-sm text-app-muted">Belum ada tiket.</p>:<div className="space-y-2">{tickets.map(t=><button key={t.id} onClick={()=>openTicket(t)} className={`w-full rounded-2xl border p-3 text-left transition ${selected?.id===t.id?"border-gold-400 bg-gold-400/10":"border-app-border hover:border-gold-400/40"}`}><div className="flex items-center justify-between gap-2"><b className="text-sm">{t.ticket_number}</b><span className="rounded-full bg-app-inset px-2 py-1 text-[10px] font-bold text-app-muted">{statuses[t.status]||t.status}</span></div><p className="mt-1 truncate text-sm font-semibold text-app-text">{t.subject}</p><p className={`mt-1 text-[11px] ${t.category==="PENGADUAN"?"font-bold text-red-600 dark:text-red-400":"text-app-subtle"}`}>{t.category==="PENGADUAN"?"⚠️ PENGADUAN":t.category} · {formatDate(t.last_message_at)}</p></button>)}</div>}</div></div>
 <div className="rounded-3xl border border-app-border bg-app-surface shadow-sm">{!selected?<div className="flex min-h-[520px] items-center justify-center p-8 text-center text-sm text-app-muted">Pilih tiket untuk melihat percakapan.</div>:<div className="flex min-h-[520px] flex-col"><div className="border-b border-app-border p-5"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-xs font-bold text-app-kicker">{selected.ticket_number}</p><h2 className="text-xl font-black text-app-text">{selected.subject}</h2></div><div className="flex items-center gap-2"><span className="rounded-full bg-app-inset px-3 py-1 text-xs font-bold text-app-muted">{statuses[selected.status]||selected.status}</span>{selected.status==="CLOSED"?<button onClick={reopenTicket} disabled={sending} className="inline-flex min-h-[36px] items-center justify-center gap-2 rounded-xl bg-gold-400 px-3 py-1.5 text-xs font-black text-zinc-950 transition hover:bg-gold-300 disabled:cursor-not-allowed disabled:opacity-50">{sending&&<span className="h-3.5 w-3.5 animate-spin rounded-full border-2 border-zinc-950/30 border-t-zinc-950"/>}Buka Kembali</button>:<button onClick={closeTicket} disabled={sending} className="rounded-xl border border-app-border px-3 py-1.5 text-xs font-bold text-app-muted transition hover:border-gold-400/60 hover:text-app-kicker">Tutup Tiket</button>}</div></div></div><div className="flex-1 space-y-3 overflow-y-auto p-5">{messages.map(m=><div key={m.id} className={`max-w-[85%] rounded-2xl p-3 ${m.sender_role==="USER"?"ml-auto bg-gold-400 text-zinc-950":"bg-app-inset text-app-text"}`}><p className="whitespace-pre-wrap text-sm">{m.message}</p><p className={`mt-1 text-[10px] ${m.sender_role==="USER"?"text-zinc-950/60":"text-app-subtle"}`}>{m.sender_role==="ADMIN"?"Admin":"Anda"} · {formatDate(m.created_at)}</p></div>)}</div>{!['CLOSED'].includes(selected.status)&&<div className="border-t border-app-border p-4"><textarea value={message} onChange={e=>setMessage(e.target.value)} rows={3} placeholder="Tulis balasan..." className="w-full rounded-xl border border-app-border bg-app-inset px-3 py-2.5 text-sm text-app-text outline-none transition placeholder:text-app-subtle focus:border-gold-400 focus:ring-4 focus:ring-gold-400/20"/><button onClick={reply} disabled={sending} className="mt-2 inline-flex min-h-[44px] w-full items-center justify-center gap-2 rounded-xl bg-gold-400 px-4 py-3 text-sm font-black text-zinc-950 transition hover:bg-gold-300 disabled:cursor-not-allowed disabled:opacity-50">{sending&&<span className="h-4 w-4 animate-spin rounded-full border-2 border-zinc-950/30 border-t-zinc-950"/>}Kirim Balasan</button></div>}</div>}</div></div></div></div>;
}
