'use client';
import {useEffect,useState} from 'react';
export default function MonitoringPage(){
 const [d,setD]=useState<any>({alerts:[],runs:[],summary:{open:0,critical:0,warning:0}}); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState('');
 async function load(){const r=await fetch('/api/admin/monitoring',{cache:'no-store'});if(r.ok)setD(await r.json());}
 async function run(){setBusy(true);setMsg('');try{const r=await fetch('/api/admin/monitoring',{method:'POST'});const j=await r.json();setMsg(r.ok?`Pemeriksaan selesai • ${j.alerts_opened} alert diperbarui.`:(j.message||'Gagal'));await load()}finally{setBusy(false)}}
 async function resolve(id:string){const r=await fetch(`/api/admin/monitoring/${id}`,{method:'PATCH'});if(r.ok)load()}
 useEffect(()=>{load();const t=setInterval(load,30000);return()=>clearInterval(t)},[]);
 return <div className="space-y-5"><div className="rounded-3xl bg-gradient-to-r from-slate-950 via-slate-900 to-zinc-950 p-6 text-white"><p className="text-xs font-black uppercase tracking-[.2em] text-amber-300">OPERATIONS CENTER</p><h1 className="mt-2 text-2xl font-black">Monitoring & Notification Center</h1><p className="mt-2 text-sm text-white/65">Pantau mismatch pembayaran, refund tertunda, webhook error, transaksi PPOB yang terlalu lama, dan sinkronisasi provider.</p></div>
 <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border bg-white p-5"><p className="text-xs text-slate-400">Open Alert</p><p className="text-3xl font-black">{d.summary.open}</p></div><div className="rounded-2xl border bg-white p-5"><p className="text-xs text-slate-400">Critical</p><p className="text-3xl font-black">{d.summary.critical}</p></div><div className="rounded-2xl border bg-white p-5"><p className="text-xs text-slate-400">Warning</p><p className="text-3xl font-black">{d.summary.warning}</p></div></div>
 <section className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-black">Pemeriksaan sistem</h2><p className="text-sm text-slate-500">Jalankan pengecekan database secara manual. Cron dapat memanggil endpoint ini secara berkala.</p></div><button onClick={run} disabled={busy} className="rounded-xl bg-gold-600 px-4 py-3 text-sm font-bold text-white disabled:opacity-60">{busy?'Memeriksa...':'🔎 Jalankan Monitoring'}</button></div>{msg&&<p className="mt-3 rounded-xl bg-slate-50 p-3 text-sm font-semibold">{msg}</p>}</section>
 <section className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b text-left text-xs text-slate-400"><th className="p-4">Severity</th><th className="p-4">Kategori</th><th className="p-4">Alert</th><th className="p-4">Terakhir</th><th className="p-4">Status</th><th className="p-4"></th></tr></thead><tbody>{d.alerts.map((x:any)=><tr key={x.id} className="border-b"><td className="p-4 font-black">{x.severity}</td><td className="p-4">{x.category}</td><td className="p-4"><b>{x.title}</b><p className="text-xs text-slate-500">{x.message}</p></td><td className="p-4 text-xs">{new Date(x.last_seen_at).toLocaleString('id-ID')}</td><td className="p-4">{x.status}</td><td className="p-4">{x.status!=='RESOLVED'&&<button onClick={()=>resolve(x.id)} className="rounded-lg border px-3 py-2 text-xs font-bold">Resolve</button>}</td></tr>)}</tbody></table>{!d.alerts.length&&<p className="p-8 text-center text-sm text-slate-400">Belum ada alert.</p>}</section>
 </div>
}
