"use client";

import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { useToast } from "@/components/ToastProvider";
import Button from "@/components/Button";
import EmptyState from "@/components/EmptyState";
import { formatDate, humanizeError } from "@/lib/utils";

type Ticket={id:string;ticket_number:string;subject:string;category:string;priority:string;status:string;order_id:string|null;created_at:string;last_message_at:string;profiles:{full_name:string|null;email:string}|null};
type Msg={id:string;sender_role:string;message:string;created_at:string};
const STATUS=["OPEN","IN_PROGRESS","WAITING_CUSTOMER","RESOLVED","CLOSED"];
const statusLabel:Record<string,string>={OPEN:"Open",IN_PROGRESS:"Diproses",WAITING_CUSTOMER:"Menunggu pelanggan",RESOLVED:"Selesai",CLOSED:"Ditutup"};

export default function AdminSupportPage(){const supabase=createClient();const toast=useToast();const [tickets,setTickets]=useState<Ticket[]>([]);const [selected,setSelected]=useState<Ticket|null>(null);const [messages,setMessages]=useState<Msg[]>([]);const [reply,setReply]=useState("");const [filter,setFilter]=useState("OPEN");const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);
 async function load(){setLoading(true);let q=supabase.from("support_tickets").select("id,ticket_number,subject,category,priority,status,order_id,created_at,last_message_at,profiles(full_name,email)").order("last_message_at",{ascending:false});if(filter!=="ALL")q=q.eq("status",filter);const {data,error}=await q;if(error)toast.show(humanizeError(error.message),"error");setTickets((data as Ticket[])||[]);setLoading(false)}
 async function open(t:Ticket){setSelected(t);const {data,error}=await supabase.from("support_ticket_messages").select("id,sender_role,message,created_at").eq("ticket_id",t.id).order("created_at",{ascending:true});if(error)toast.show(humanizeError(error.message),"error");setMessages((data as Msg[])||[])}
 useEffect(()=>{load();/* eslint-disable-next-line react-hooks/exhaustive-deps */},[filter]);
 async function send(){if(!selected||!reply.trim())return;setSaving(true);try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Sesi admin tidak ditemukan");const {error}=await supabase.from("support_ticket_messages").insert({ticket_id:selected.id,sender_id:user.id,sender_role:"ADMIN",message:reply.trim(),is_internal:false});if(error)throw error;await supabase.rpc("touch_support_ticket",{p_ticket_id:selected.id,p_sender_role:"ADMIN",p_message:reply.trim()});setReply("");await open(selected);await load();}catch(e:any){toast.show(humanizeError(e?.message),"error")}finally{setSaving(false)}}
 async function setStatus(status:string){if(!selected)return;setSaving(true);try{const {data,error}=await supabase.rpc("set_support_ticket_status",{p_ticket_id:selected.id,p_status:status});if(error)throw error;setSelected(data as Ticket);toast.show("Status tiket diperbarui.","success");await load();}catch(e:any){toast.show(humanizeError(e?.message),"error")}finally{setSaving(false)}}
 return <div className="space-y-5 pb-10"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="section-kicker">Customer Support</p><h1 className="text-2xl font-black">Ticket Center</h1><p className="mt-1 text-sm text-slate-500">Kelola percakapan pelanggan, status, prioritas, dan referensi order dari satu tempat.</p></div><div className="flex flex-wrap gap-2"><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-bold"><option value="OPEN">Open</option>{STATUS.filter(s=>s!=="OPEN").map(s=><option key={s} value={s}>{statusLabel[s]}</option>)}<option value="ALL">Semua</option></select><button onClick={load} className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-bold">↻ Refresh</button></div></div>
 <div className="grid gap-5 lg:grid-cols-[380px_1fr]"><div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">{loading?<p className="p-4 text-sm text-slate-500">Memuat tiket...</p>:tickets.length===0?<EmptyState title="Tidak ada tiket"/>:<div className="space-y-2">{tickets.map(t=><button key={t.id} onClick={()=>open(t)} className={`w-full rounded-2xl border p-3 text-left ${selected?.id===t.id?"border-gold-300 bg-gold-50":"border-slate-200 hover:bg-slate-50"}`}><div className="flex justify-between gap-2"><b>{t.ticket_number}</b><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold">{t.priority}</span></div><p className="mt-1 text-sm font-bold">{t.subject}</p><p className="mt-1 text-xs text-slate-500">{t.profiles?.full_name||t.profiles?.email||"Pengguna"} · {t.category}</p><p className="mt-1 text-[10px] text-slate-400">{formatDate(t.last_message_at)}</p></button>)}</div>}</div>
 <div className="rounded-2xl border border-slate-200 bg-white shadow-sm">{!selected?<div className="flex min-h-[560px] items-center justify-center p-8 text-center text-sm text-slate-400">Pilih tiket untuk menangani percakapan.</div>:<div className="flex min-h-[560px] flex-col"><div className="border-b p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-bold text-gold-600">{selected.ticket_number}</p><h2 className="text-xl font-black">{selected.subject}</h2><p className="mt-1 text-xs text-slate-500">{selected.profiles?.full_name||selected.profiles?.email} · {selected.category}{selected.order_id?` · Order ${selected.order_id}`:""}</p></div><div className="flex gap-2"><select disabled={saving} value={selected.status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold">{STATUS.map(s=><option key={s}>{s}</option>)}</select></div></div></div><div className="flex-1 space-y-3 overflow-y-auto p-5">{messages.map(m=><div key={m.id} className={`max-w-[85%] rounded-2xl p-3 ${m.sender_role==="ADMIN"?"ml-auto bg-gold-600 text-white":"bg-slate-100 text-slate-800"}`}><p className="whitespace-pre-wrap text-sm">{m.message}</p><p className={`mt-1 text-[10px] ${m.sender_role==="ADMIN"?"text-gold-100":"text-slate-400"}`}>{m.sender_role} · {formatDate(m.created_at)}</p></div>)}</div>{selected.status!=="CLOSED"&&<div className="border-t p-4"><textarea value={reply} onChange={e=>setReply(e.target.value)} rows={3} placeholder="Balas pelanggan..." className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm"/><Button onClick={send} className="mt-2 w-full" loading={saving}>Kirim Balasan</Button></div>}</div>}</div></div></div>}
