"use client";
import { useEffect, useState } from "react";
const rupiah=(n:number)=>`Rp${Number(n||0).toLocaleString("id-ID")}`;
export default function ReconciliationPage(){
 const [data,setData]=useState<any>(null); const [loading,setLoading]=useState(true); const [running,setRunning]=useState(false); const [message,setMessage]=useState("");
 async function load(){setLoading(true);const r=await fetch('/api/admin/reconciliation',{cache:'no-store'});setData(await r.json());setLoading(false)}
 async function run(){setRunning(true);setMessage("");const r=await fetch('/api/admin/reconciliation/run',{method:'POST'});const j=await r.json();setMessage(j.ok?`Scan selesai: ${j.checked_count} record diperiksa${j.error_count?`, ${j.error_count} error`:``}.`:j.message||"Scan gagal.");await load();setRunning(false)}
 async function retry(refund_id:string){const r=await fetch('/api/admin/reconciliation/refund',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refund_id})});const j=await r.json();setMessage(j.message||"Selesai.");await load()}
 useEffect(()=>{load()},[]);
 if(loading)return <div className="rounded-2xl border bg-white p-6 text-sm text-slate-500">Memuat rekonsiliasi...</div>;
 if(data?.message)return <div className="rounded-2xl border border-amber-200 bg-amber-50 p-6 text-sm text-amber-900">{data.message}</div>;
 return <div className="space-y-5 pb-10"><div className="flex items-end justify-between gap-3"><div><p className="section-kicker">Keuangan</p><h1 className="text-2xl font-black">Reconciliation & Refund Center</h1><p className="mt-1 text-sm text-slate-500">Pakasir ↔ AIDIL STORE ↔ Digiflazz ↔ Wallet.</p></div><div className="flex gap-2"><button onClick={load} className="rounded-xl border bg-white px-4 py-2 text-sm font-bold">↻ Refresh</button><button onClick={run} disabled={running} className="rounded-xl bg-gold-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-60">{running?"Scanning...":"▶ Jalankan Rekonsiliasi"}</button></div></div>{message&&<div className="rounded-xl border border-gold-100 bg-gold-50 p-3 text-sm text-zinc-900">{message}</div>}
 <div className="grid gap-3 sm:grid-cols-3"><Card t="Matched" v={data.summary.matched}/><Card t="Perlu review" v={data.summary.mismatches}/><Card t="Refund" v={data.summary.refunds}/></div>
 <section className="rounded-2xl border bg-white p-5"><h2 className="font-black">Reconciliation</h2><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b text-left text-xs text-slate-400"><th className="p-3">Sumber</th><th className="p-3">Status Internal</th><th className="p-3">Provider</th><th className="p-3">Internal</th><th className="p-3">Provider</th><th className="p-3">State</th><th className="p-3">Catatan</th></tr></thead><tbody>{(data.reconciliation||[]).map((r:any)=><tr key={r.id} className="border-b"><td className="p-3 font-bold">{r.source_type}</td><td className="p-3">{r.internal_status||'-'}</td><td className="p-3">{r.provider||'-'}</td><td className="p-3">{rupiah(r.internal_amount)}</td><td className="p-3">{rupiah(r.provider_amount)}</td><td className="p-3"><span className={`rounded-full px-2 py-1 text-xs font-bold ${r.state==='MATCHED'?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-700'}`}>{r.state}</span></td><td className="p-3 text-xs text-slate-500">{r.discrepancy||'-'}</td></tr>)}</tbody></table>{!data.reconciliation?.length&&<p className="py-8 text-center text-sm text-slate-400">Belum ada hasil rekonsiliasi.</p>}</div></section>
 <section className="rounded-2xl border bg-white p-5"><h2 className="font-black">Refund Center</h2><div className="mt-3 space-y-2">{(data.refunds||[]).map((r:any)=><div key={r.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-slate-50 p-3"><div><b>{rupiah(r.amount)}</b><p className="text-xs text-slate-500">Order {r.order_id} · {r.reason}</p></div><div className="flex items-center gap-2"><span className="rounded-full bg-white px-3 py-1 text-xs font-black">{r.status}</span>{r.status==="FAILED"&&<button onClick={()=>retry(r.id)} className="rounded-lg bg-red-600 px-2 py-1 text-[11px] font-bold text-white">Retry</button>}</div></div>)}{!data.refunds?.length&&<p className="py-8 text-center text-sm text-slate-400">Belum ada refund.</p>}</div></section>
 </div>
}
function Card({t,v}:{t:string,v:any}){return <div className="rounded-2xl border bg-white p-5"><p className="text-xs font-bold text-slate-500">{t}</p><p className="mt-1 text-2xl font-black">{v}</p></div>}
